services:

  openai_service:
    build: .
    # image: node:18-alpine
    restart: always
    ports:
      - 40003:40003
    volumes:
      - ./src:/app/scr
      - ./custom_module:/app/scr/custom_module
    # command: nodemon ./scr/server.js
